### ISSUE TITLE
Waypoint animation not working

### ISSUE THREAD

**Issue by bradley-doyle** [bradley-doyle/dsn1676-term-project#3]
@thomasjbradley I have been trying to figure out why the classes are applying/removing when the waypoint it hit. 

I checked to see with a console.log for the waypoint and that it was being triggered, it was being triggered but the if/else statement wasn't

**Comment by thomasjbradley** [comment]
Where's the waypoint in your JS code?

**Comment by bradley-doyle** [comment]
should be at the bottom of main know. sorry about that.

**Comment by thomasjbradley** [comment]
It's because the code is manipulating the SVG directly and `addClass` doesn't work on SVGs.

Try adding the class to a `div` or something that surrounds the SVG instead.

**Comment by bradley-doyle** [comment]
Awesome got it working. I keep forgetting that svg's get treated a little different then normal elements
