### ISSUE TITLE
Padding not applying to all sides

### ISSUE THREAD

**Issue by bradley-doyle** [bradley-doyle/dsn1676-term-project#4]
@thomasjbradley I know that school hasn't started but I have no idea why my island padding isn't applying to all sides of my Welcome text on my billboard image

The line in question is 47 in my html 

``` html
  <div class="billboard">
    <div class="large-screen-b">
      <div class="grid-bottom">
        <div class="unit unit-xs-1 unit-s-1 unit-m-1 unit-l-1 unit-xl-1 island">
          <h2 class="push-0 island-half billboard-type zetta burr">WELCOME</h2>
        </div>
      </div>
    </div>
  </div>
```

any help would be awesome.

**Comment by bradley-doyle** [comment]
I have fixed the problem. I had a width of 100% on the element and then padding on top of that making it shoot off the screen.

sorry for the email ahah

**Comment by thomasjbradley** [comment]
Glad you fixed it!

But with `box-sizing: border-box` the padding should be inside the width. I wonder why it was causing it to be too big...

**Comment by bradley-doyle** [comment]
Thanks!
